---
# Generate renew cert file
- name: create '/opt/certbot-update.sh'
  template:
    src: certbot-update.sh.j2
    dest: "/opt/certbot-update.sh"
    mode: '0700'

- name: create '/etc/letsencrypt/list-domain-with-ssl'
  template:
    src: list-domain-with-ssl.j2
    dest: "/etc/letsencrypt/list-domain-with-ssl"

- name: update certificates
  shell: /opt/certbot-update.sh

# Set cron to auto-renew
- name: create auto-renew job
  cron:
    name: "nginx certificates auto-renew"
    special_time: weekly
    job: 'certbot renew --pre-hook "service nginx stop" --post-hook "service nginx start"'
