---

# Install required system packages
- name: add goaccess repository key
  apt_key:
    url: https://deb.goaccess.io/gnugpg.key
    state: present

- name: add goaccess repository
  apt_repository:
    repo: "deb http://deb.goaccess.io/ {{ ansible_distribution_release|lower }} main"
    state: present
    filename: goaccess

- name: install goaccess
  apt:
    name: goaccess
    state: latest
    update_cache: true

- name: install apache2-utils
  apt:
    name: apache2-utils
    state: present
    update_cache: true

# Install Ansible requirements packages
- name: install pip
  apt:
    name: python-pip
    state: present
    update_cache: true

- name: (pip) install passlib for Ansible integration
  pip:
    name: passlib
    state: latest

# Setup goaccess
- name: create report dir '/var/www/goaccess/'
  file:
    path: /var/www/goaccess/
    state: directory
    mode: 0755

- name: create '/etc/systemd/system/goaccess.service'
  template:
    src: goaccess/goaccess.service.j2
    dest: "/etc/systemd/system/goaccess.service"
    mode: '0700'

- name: create '/etc/goaccess.conf'
  template:
    src: goaccess/goaccess.conf.j2
    dest: "/etc/goaccess.conf"
    mode: '0700'

- name: enable and start/restart goaccess service
  systemd:
    name: goaccess
    state: restarted
    enabled: true
    daemon_reload: true
  when: not molecule_test
