---
- name: install Certbot
  apt:
    name: certbot
    state: present
    update_cache: true

- name: install Nginx plugin for Certbot
  apt:
    name: python3-certbot-nginx
    state: present
    update_cache: true
