---

# I don't know how to do this for all Ubuntu regions
# using some Ansible module.
- name: add Universe repo
  shell: add-apt-repository universe

- name: install Certbot
  apt:
    name: certbot
    state: present
    update_cache: true

- name: install Nginx plugin for Certbot
  apt:
    name: python3-certbot-nginx
    state: present
    update_cache: true
