---
# Based on "miguelenes" repo:
# https://github.com/miguelenes/ansible-role-nginx-pagespeed/blob/master/handlers/main.yml

- name: apt-get update
  apt:
    update_cache: yes

- name: install base packages
  apt:
    name: "{{item}}"
    state: installed
  with_items:
       - nginx
       - unzip
       - gcc
       - make
       - libpcre3-dev
       - zlib1g-dev
       - uuid-dev

- name: check nginx version compatibility
  shell: /usr/sbin/nginx -v 2>&1
  register: nginxVersion

- name: get nginxVersion
  set_fact:
    nginxVersion: "{{ nginxVersion.stdout.split('/').1 }}"

- name: check if PageSpeed is compatible
  fail:
    msg: "Cannot install google page speed module without nginx version higher than 1.11.5"
  when: nginxVersion == "" or {{ nginxVersion | version_compare('1.11.5', '<') }}

- name: download and unarchive google pagespeed
  unarchive:
    src: "https://github.com/pagespeed/ngx_pagespeed/archive/v{{ google_pagespeed_version }}.zip"
    dest: /tmp
    remote_src: yes

- name: download and unarchive google pagespeed
  shell: "cd /tmp/incubator-pagespeed-ngx-{{ google_pagespeed_version }} &&
          psol_url=https://dl.google.com/dl/page-speed/psol/${NPS_VERSION}.tar.gz
          [ -e scripts/format_binary_url.sh ] && psol_url=$(scripts/format_binary_url.sh PSOL_BINARY_URL) &&
           wget ${psol_url} && tar -xzvf $(basename ${psol_url})"

- name: configure nginx
  command: ./configure --add-dynamic-module=../incubator-pagespeed-ngx-{{ google_pagespeed_version }} --with-compat
  args:
    chdir: "/tmp/nginx-{{ nginxVersion }}"

- name: copy extension to nginx modules
  copy: 
    remote_src: true
    src: "/tmp/nginx-{{ nginxVersion }}/objs/ngx_pagespeed.so"
    dest: "/etc/nginx/modules/ngx_pagespeed.so"

- name: enable extension
  file: 
    src: /etc/nginx/modules/ngx_pagespeed.so 
    dest: /etc/nginx/modules-available/ngx_pagespeed.so 
    state: link
  notify: restart nginx

- name: remove build files
  file: 
    path: "/tmp/nginx-{{ nginxVersion }}" 
    state: absent

- name: remove build files
  file: 
    path: "/tmp/incubator-pagespeed-ngx-{{ google_pagespeed_version }}" 
    state: absent
