---

# Install Nginx
- include_tasks: install-nginx.yml

# Install Certbot
- include_tasks: install-certbot.yml

# Install PageSpeed
- include_tasks: install-pagespeed.yml
  when: install_pagespeed

# Generate certificates
- include_tasks: generate-certs.yml
  when: acme_email != ""

# Setup Nginx sites
- include_tasks: setup-nginx.yml

# Install goaccess
- include_tasks: install-goaccess.yml
  notify: reload nginx
