---

# Create secret files
- name: create Nginx passwd dir '/etc/nginx/passwd'
  file:
    path: /etc/nginx/passwd
    state: directory
    mode: 0755

- name: delete each keychain file if exist
  file:
    path: /etc/nginx/passwd/{{item.keychain}}
    state: absent
  loop: "{{auth}}"

- name: create secret files '/etc/nginx/passwd/<keychain_name>'
  htpasswd:
    path: "/etc/nginx/passwd/{{item.keychain}}"
    name: "{{item.user}}"
    password: "{{item.pass}}"
    owner: root
    group: www-data
    mode: 0640
  loop: "{{auth}}"

# Create each site config file
- name: delete nginx 'sites-enable' config dir
  file:
    path: /etc/nginx/sites-enabled/
    state: absent

- name: recreate nginx 'sites-enable' config dir
  file:
    path: /etc/nginx/sites-enabled/
    owner: root
    group: root
    mode: 0755
    state: directory

- name: create default nginx config
  template:
    src: nginx-default.conf.j2
    dest: "/etc/nginx/sites-enabled/default"

- name: create nginx site config
  template:
    src: "{{ item.template | default('nginx-site.conf.j2') }}"
    dest: "/etc/nginx/sites-enabled/{{item.domain}}"
  loop: "{{loadbalancer_sites}}"
  notify: reload nginx
